### ISSUE TITLE
11.3.0 (cljs): Cannot convert ECMASCRIPT_2018 feature "RegExp unicode property escape" to targeted output language

### ISSUE THREAD

**Issue by hoxu** [highlightjs/highlight.js#3372]
**Describe the issue/behavior that seems buggy**

11.3.0 causes our shadow-cljs/ClojureScript build to break with this error from closure-compiler:

```
    [:app] Build failure:
    Closure compilation failed with 1 errors
    --- node_modules/highlight_DOT_js/lib/languages/python.js:11
    Cannot convert ECMASCRIPT_2018 feature "RegExp unicode property escape" to targeted output language.
```

**Sample Code or Instructions to Reproduce**

1. `npm install highlight.js@11.3.0`
2. Build with shadow-cljs.

**Expected behavior**

Builds without error like on 11.2.0.

**Additional context**

Workaround for some may be to change shadow-cljs output language options: https://shadow-cljs.github.io/docs/UsersGuide.html#_output_language_options

Caused by commit bb4fb2291bcd7323e0e577b9abc00e89f2e2cf14

Cc: @austin-schick @joshgoebel

**Comment by joshgoebel** [comment]
Closing as answered: our code base is expected to include ES2018 features (that are in broad use), such as Unicode Regex.
